(cl:defpackage data_collection-srv
  (:use )
  (:export
   "DATACOLLECTIONSERVICE"
   "<DATACOLLECTIONSERVICE-REQUEST>"
   "DATACOLLECTIONSERVICE-REQUEST"
   "<DATACOLLECTIONSERVICE-RESPONSE>"
   "DATACOLLECTIONSERVICE-RESPONSE"
  ))

