// Generated by gencpp from file data_collection/DataCollectionService.msg
// DO NOT EDIT!


#ifndef DATA_COLLECTION_MESSAGE_DATACOLLECTIONSERVICE_H
#define DATA_COLLECTION_MESSAGE_DATACOLLECTIONSERVICE_H

#include <ros/service_traits.h>


#include <data_collection/DataCollectionServiceRequest.h>
#include <data_collection/DataCollectionServiceResponse.h>


namespace data_collection
{

struct DataCollectionService
{

typedef DataCollectionServiceRequest Request;
typedef DataCollectionServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DataCollectionService
} // namespace data_collection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_collection::DataCollectionService > {
  static const char* value()
  {
    return "87298c286f30820362a22fac263c1209";
  }

  static const char* value(const ::data_collection::DataCollectionService&) { return value(); }
};

template<>
struct DataType< ::data_collection::DataCollectionService > {
  static const char* value()
  {
    return "data_collection/DataCollectionService";
  }

  static const char* value(const ::data_collection::DataCollectionService&) { return value(); }
};


// service_traits::MD5Sum< ::data_collection::DataCollectionServiceRequest> should match
// service_traits::MD5Sum< ::data_collection::DataCollectionService >
template<>
struct MD5Sum< ::data_collection::DataCollectionServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_collection::DataCollectionService >::value();
  }
  static const char* value(const ::data_collection::DataCollectionServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_collection::DataCollectionServiceRequest> should match
// service_traits::DataType< ::data_collection::DataCollectionService >
template<>
struct DataType< ::data_collection::DataCollectionServiceRequest>
{
  static const char* value()
  {
    return DataType< ::data_collection::DataCollectionService >::value();
  }
  static const char* value(const ::data_collection::DataCollectionServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_collection::DataCollectionServiceResponse> should match
// service_traits::MD5Sum< ::data_collection::DataCollectionService >
template<>
struct MD5Sum< ::data_collection::DataCollectionServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_collection::DataCollectionService >::value();
  }
  static const char* value(const ::data_collection::DataCollectionServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_collection::DataCollectionServiceResponse> should match
// service_traits::DataType< ::data_collection::DataCollectionService >
template<>
struct DataType< ::data_collection::DataCollectionServiceResponse>
{
  static const char* value()
  {
    return DataType< ::data_collection::DataCollectionService >::value();
  }
  static const char* value(const ::data_collection::DataCollectionServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_COLLECTION_MESSAGE_DATACOLLECTIONSERVICE_H
